/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrialsRouteImport } from './routes/admin.trials'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AppServicosRouteImport } from './routes/_app/servicos'
import { Route as AppRecorrenciasRouteImport } from './routes/_app/recorrencias'
import { Route as AppPlanosRouteImport } from './routes/_app/planos'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppBancosRouteImport } from './routes/_app/bancos'
import { Route as AppAportesRouteImport } from './routes/_app/aportes'
import { Route as AdminOrganizationsIdRouteImport } from './routes/admin.organizations.$id'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'

const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrialsRoute = AdminTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppRecorrenciasRoute = AppRecorrenciasRouteImport.update({
  id: '/recorrencias',
  path: '/recorrencias',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppBancosRoute = AppBancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => AppRoute,
} as any)
const AppAportesRoute = AppAportesRouteImport.update({
  id: '/aportes',
  path: '/aportes',
  getParentRoute: () => AppRoute,
} as any)
const AdminOrganizationsIdRoute = AdminOrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/trial': typeof TrialRoute
  '/aportes': typeof AppAportesRoute
  '/bancos': typeof AppBancosRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/planos': typeof AppPlanosRoute
  '/recorrencias': typeof AppRecorrenciasRoute
  '/servicos': typeof AppServicosRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/trial': typeof TrialRoute
  '/aportes': typeof AppAportesRoute
  '/bancos': typeof AppBancosRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/planos': typeof AppPlanosRoute
  '/recorrencias': typeof AppRecorrenciasRoute
  '/servicos': typeof AppServicosRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/trial': typeof TrialRoute
  '/_app/aportes': typeof AppAportesRoute
  '/_app/bancos': typeof AppBancosRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/recorrencias': typeof AppRecorrenciasRoute
  '/_app/servicos': typeof AppServicosRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/select-org'
    | '/signup'
    | '/trial'
    | '/aportes'
    | '/bancos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/recorrencias'
    | '/servicos'
    | '/admin/organizations'
    | '/admin/trials'
    | '/admin/users'
    | '/admin/'
    | '/clientes/$id'
    | '/admin/organizations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-org'
    | '/signup'
    | '/trial'
    | '/aportes'
    | '/bancos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/recorrencias'
    | '/servicos'
    | '/admin/organizations'
    | '/admin/trials'
    | '/admin/users'
    | '/admin'
    | '/clientes/$id'
    | '/admin/organizations/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/select-org'
    | '/signup'
    | '/trial'
    | '/_app/aportes'
    | '/_app/bancos'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/planos'
    | '/_app/recorrencias'
    | '/_app/servicos'
    | '/admin/organizations'
    | '/admin/trials'
    | '/admin/users'
    | '/admin/'
    | '/_app/clientes/$id'
    | '/admin/organizations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectOrgRoute: typeof SelectOrgRoute
  SignupRoute: typeof SignupRoute
  TrialRoute: typeof TrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trials': {
      id: '/admin/trials'
      path: '/trials'
      fullPath: '/admin/trials'
      preLoaderRoute: typeof AdminTrialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recorrencias': {
      id: '/_app/recorrencias'
      path: '/recorrencias'
      fullPath: '/recorrencias'
      preLoaderRoute: typeof AppRecorrenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bancos': {
      id: '/_app/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof AppBancosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aportes': {
      id: '/_app/aportes'
      path: '/aportes'
      fullPath: '/aportes'
      preLoaderRoute: typeof AppAportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/organizations/$id': {
      id: '/admin/organizations/$id'
      path: '/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminOrganizationsIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAportesRoute: typeof AppAportesRoute
  AppBancosRoute: typeof AppBancosRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppRecorrenciasRoute: typeof AppRecorrenciasRoute
  AppServicosRoute: typeof AppServicosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAportesRoute: AppAportesRoute,
  AppBancosRoute: AppBancosRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppRecorrenciasRoute: AppRecorrenciasRoute,
  AppServicosRoute: AppServicosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsIdRoute: typeof AdminOrganizationsIdRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsIdRoute: AdminOrganizationsIdRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminTrialsRoute: typeof AdminTrialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminTrialsRoute: AdminTrialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectOrgRoute: SelectOrgRoute,
  SignupRoute: SignupRoute,
  TrialRoute: TrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
