// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twgcxnoctlkbrtaapxik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Z2N4bm9jdGxrYnJ0YWFweGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxNjY4NjIsImV4cCI6MjA5NTc0Mjg2Mn0.g7OYrjRRnnq8psqNwKiHuWcujuvOBuL5aTgP-wcEd58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});